# Generated by Django 5.2 on 2025-05-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_printer', '0003_labeltemplate_barcode_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labeltemplate',
            name='label_whight',
        ),
        migrations.AddField(
            model_name='labeltemplate',
            name='label_wight',
            field=models.CharField(default='240', help_text='Указывается в точках', max_length=20),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='label_hight',
            field=models.CharField(default='160', help_text='Указывается в точках', max_length=20),
        ),
    ]
