# Generated by Django 5.2 on 2025-05-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_printer', '0004_remove_labeltemplate_label_whight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeltemplate',
            name='date_font_size',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='label_hight',
            field=models.CharField(blank=True, default='160', help_text='Указывается в точках', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='label_wight',
            field=models.CharField(blank=True, default='240', help_text='Указывается в точках', max_length=20, null=True),
        ),
    ]
