# Generated by Django 5.2 on 2025-05-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_printer', '0005_alter_labeltemplate_date_font_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeltemplate',
            name='barcode_type',
            field=models.CharField(choices=[('CODE128', 'CODE128'), ('CODE39', 'CODE39'), ('EAN13', 'EAN13')], default='EAN13', max_length=50),
        ),
    ]
