# Generated by Django 5.2 on 2025-05-09 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label_printer', '0006_alter_labeltemplate_barcode_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labeltemplate',
            name='barcode_type',
        ),
    ]
