# Generated by Django 5.2 on 2025-05-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_printer', '0007_remove_labeltemplate_barcode_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeltemplate',
            name='product_name_via_pillow',
            field=models.BooleanField(default=False, help_text='Имя товара генируется в виде изображения и подставляется в этикетку, применимо, в случае, если в принтер не загружен русский шрифт (есть проблемы с центровкой и качеством шрифта)'),
        ),
    ]
