# Generated by Django 5.2 on 2025-05-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_printer', '0008_labeltemplate_product_name_via_pillow'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelPrintLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=128)),
                ('printed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
