# Generated by Django 5.2 on 2025-05-12 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_printer', '0009_labelprintlog'),
        ('products', '0009_alter_product_barcode_alter_product_barcode15_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelprintlog',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prints', to='products.product'),
        ),
    ]
