# Generated by Django 5.2 on 2025-05-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode15',
            field=models.CharField(default=1212211212, max_length=50),
            preserve_default=False,
        ),
    ]
