# Generated by Django 5.2 on 2025-05-09 20:49

import cropperjs.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_delete_printer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cropperjs.models.CropperImageField(upload_to='product_images/'),
        ),
    ]
