# Generated by Django 5.2 on 2025-05-09 21:29

import cropperjs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(help_text='Артикул для тары 1 литр', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode15',
            field=models.CharField(help_text='Артикул для тары 1.5 литра', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Описание товара, отображается при выборе товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cropperjs.models.CropperImageField(aspectratio='1.0', dimensions=(350, 350), upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Наименование товара', max_length=100),
        ),
    ]
