# Generated by Django 5.2 on 2025-05-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_printer'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='type',
            field=models.CharField(choices=[('USB', 'USB'), ('NETWORK', 'Network')], default='USB', max_length=10),
        ),
    ]
