# Generated by Django 5.2 on 2025-05-07 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_printer_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Printer',
        ),
    ]
