# Generated by Django 5.2 on 2025-05-13 12:28

import cropperjs.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_barcode_alter_product_barcode15_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cropperjs.models.CropperImageField(aspectratio='1.0', dimensions=(250, 250), upload_to='product_images/'),
        ),
    ]
