# Generated by Django 5.2 on 2026-09-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название тары, например: 1 литр, 1.5 литра, 500 г', max_length=20)),
                ('value', models.PositiveIntegerField(help_text='Значение в миллилитрах или граммах')),
                ('type', models.CharField(choices=[('volume', 'Миллилитры'), ('weight', 'Граммы')], help_text='Единица измерения значения', max_length=10)),
            ],
        ),
    ]
