# Generated by Django 5.2 on 2026-09-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_tare'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_product',
            field=models.BooleanField(default=False, help_text='Весовой товар EAN13, при формировании штрихкода последние 5 цифр определяются нажатой кнопкой в интерфейсе. Контрольная цифра (13) расчитывается автоматически'),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(help_text='Артикул товара', max_length=13),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode15',
            field=models.CharField(help_text='Артикул для тары 1.5 литра', max_length=13),
        ),
    ]
