# Generated by Django 5.2 on 2025-05-09 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('font_name', models.CharField(default='E:TT0003M_.FNT', max_length=50)),
                ('font_letter', models.CharField(default='0', max_length=1)),
                ('barcode_type', models.CharField(choices=[('CODE128', 'CODE128'), ('CODE39', 'CODE39')], default='CODE128', max_length=50)),
                ('barcode_height', models.PositiveIntegerField(default=100)),
                ('barcode_human_readable', models.BooleanField(default=True)),
                ('product_name_font_size', models.PositiveIntegerField(default=30)),
                ('date_font_size', models.PositiveIntegerField(default=20)),
                ('date_format', models.CharField(default='%d/%m/%Y', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=9100)),
                ('is_active', models.BooleanField(default=True)),
                ('label_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='label_printer.labeltemplate')),
            ],
        ),
    ]
