# Generated by Django 5.2 on 2025-05-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_printer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='connection_type',
            field=models.CharField(choices=[('network', 'Сетевой принтер'), ('usb', 'USB-принтер')], default='network', max_length=7),
        ),
        migrations.AddField(
            model_name='printer',
            name='device_path',
            field=models.CharField(blank=True, help_text='Пример: /dev/usb/lp0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='port',
            field=models.IntegerField(blank=True, default=9100, null=True),
        ),
    ]
