# Generated by Django 5.2 on 2025-05-09 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_printer', '0002_printer_connection_type_printer_device_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeltemplate',
            name='barcode_position',
            field=models.CharField(default='20,1', help_text='Указывается в точках в формате 0,0 (^FOx,y)', max_length=20),
        ),
        migrations.AddField(
            model_name='labeltemplate',
            name='date_position',
            field=models.CharField(default='70,10', help_text='Указывается в точках в формате 0,0 (^FOx,y)', max_length=20),
        ),
        migrations.AddField(
            model_name='labeltemplate',
            name='label_hight',
            field=models.CharField(default='70,10', help_text='Указывается в точках в формате 0,0 (^FOx,y)', max_length=20),
        ),
        migrations.AddField(
            model_name='labeltemplate',
            name='label_whight',
            field=models.CharField(default='70,10', help_text='Указывается в точках в формате 0,0 (^FOx,y)', max_length=20),
        ),
        migrations.AddField(
            model_name='labeltemplate',
            name='product_position',
            field=models.CharField(default='20,1', help_text='Указывается в точках в формате 0,0 (^FOx,y)', max_length=20),
        ),
        migrations.AddField(
            model_name='printer',
            name='printer_dpi',
            field=models.CharField(choices=[('203', '203 dpi — 1 точка ≈ 0.125 мм'), ('300', '300 dpi — 1 точка ≈ 0.085 мм')], default='203', help_text='Разрешение принтера (пока не учитывается)', max_length=3),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='date_format',
            field=models.CharField(default='%d/%m/%y-%H:%M', max_length=50),
        ),
        migrations.AlterField(
            model_name='printer',
            name='address',
            field=models.CharField(blank=True, help_text='Указать IP или Hostname/DNS', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Поставить чекбокс для используемого принтера, если подлкючен USB принтер и активны сетевой и USB, приоритет у USB принтера. Если USB принтер не подключен, но выбран как Active, скорее всего будет ошибка и печать не уйдет на сетевой принтер (надо проверить)'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='label_template',
            field=models.ForeignKey(help_text='Для каждого принтера могут быть свои настройки этикетки', null=True, on_delete=django.db.models.deletion.SET_NULL, to='label_printer.labeltemplate'),
        ),
    ]
