# Generated by Django 5.2 on 2025-05-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_printer', '0010_labelprintlog_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labelprintlog',
            name='product',
        ),
        migrations.AddField(
            model_name='labelprintlog',
            name='volume',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
