# Generated by Django 5.2 on 2025-05-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_printer', '0011_remove_labelprintlog_product_labelprintlog_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelprintlog',
            name='printed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время печати'),
        ),
    ]
