# Generated by Django 5.2 on 2025-09-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_printer', '0012_alter_labelprintlog_printed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelprintlog',
            name='volume',
            field=models.IntegerField(verbose_name='Объём (мл)'),
        ),
    ]
