# Generated by Django 5.2 on 2026-09-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_printer', '0014_emailserverconfig_emailrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeltemplate',
            name='barcode_control_digit',
            field=models.CharField(choices=[('Y', 'Проверять контрольную сумму'), ('N', 'Отключить проверку контрольной суммы'), ('B', 'Проверять контрольную сумму и печатать текст над штрихкодом')], default='N', help_text='При включении пересчитывает 13 цифру штрихкода EAN13', max_length=1),
        ),
    ]
