# Generated by Django 5.2 on 2026-09-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_printer', '0015_labeltemplate_barcode_control_digit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeltemplate',
            name='barcode_control_digit',
            field=models.CharField(choices=[('Y', 'Проверять контрольную сумму'), ('N', 'Отключить проверку контрольной суммы')], default='N', help_text='При включении пересчитывает 13 цифру штрихкода EAN13', max_length=1),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='barcode_human_readable',
            field=models.BooleanField(default=True, help_text='Печатать название товара под штрихкодом'),
        ),
    ]
